### PR TITLE
Add Deon badge usage instructions

### LINKED ISSUE #79: Create 'ethics checklist' badge for projects to display
Is was mentioned in the  [podcast.__init__ episode on Deon](https://www.podcastinit.com/deon-with-emily-miller-and-peter-bull-episode-184/), projects commonly display badges to indicate various achievements and status reports. It was suggested that we create a badge for the Deon ethics checklist, that may be (proudly) displayed in project READMEs and websites. To that end, please consider the following badge ideas:

A) ethics checklist: included brightgreen (bright green, popout-square)

B) ethics checklist included blue (blue, default)

C) ethics checklist: complete green (bright green, default)

### PR DESCRIPTION
**Pull request by brylie**
Closes #79

### CODE REVIEW

**Comment by pjbull** [comment]
Amazing, thanks @brylie! Can you run `make build` and include the updated files?

**Comment by pjbull** [comment]
(Oops, just saw your message in #79 and responded there).

**Comment by brylie** [comment]
The tests here are really difficult to get to pass. Particularly, there is whitespace being inserted in the rendered output, such as in the HTML output. This makes it quite brittle to add new text to the template.

**Comment by brylie** [comment]
I am finding myself fighting the IDE whitespace to try and get the tests to pass. It might be better if these *known good* outputs were stored in separate text files with expected formatting, rather than embedded as strings in the Python file.

**Comment by brylie** [comment]
Here is another maddening example where it seems to want and not want the empty line(s) between the badge and *A. First section':

screenshot_20181106_131908

**Comment by brylie** [comment]
ping @pjbull

**Comment by pjbull** [comment]
Thanks @brylie!

**Pull request merged**
